version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_nest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads 
    command: yarn start:dev

volumes:
  pgdata:
