import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787067006765 implements MigrationInterface {
    name = 'InitialSchema1787067006765'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "role_id" uuid NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "is_email_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(15) NOT NULL, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "size" character varying(50), "color" character varying(80), "color_hex" character varying(7), "sku" character varying(80), "price" numeric(12,2), "stock" integer NOT NULL DEFAULT '0', "image_url" character varying(500), "is_active" boolean NOT NULL DEFAULT true, "order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_46f236f21640f9da218a063a866" UNIQUE ("sku"), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "store_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8afaa45e2e49aae4eb2ac0e68b9" UNIQUE ("name", "store_id"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" integer NOT NULL, "unit_cost" numeric(12,2) NOT NULL, "line_total" numeric(12,2) NOT NULL, "expires_at" TIMESTAMP, "batch_code" character varying(120), CONSTRAINT "PK_e3d9bea880baad86ff6de3290da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_payments_payment_method_enum" AS ENUM('CASH', 'TRANSFER')`);
        await queryRunner.query(`CREATE TABLE "purchase_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "payment_method" "public"."purchase_payments_payment_method_enum" NOT NULL DEFAULT 'CASH', "note" character varying(255), "reference" character varying(120), "receipt_image_path" character varying(255), "paid_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9765d702e073d3cdf9b1600792d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchases_status_enum" AS ENUM('OPEN', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "store_id" uuid NOT NULL, "purchase_date" TIMESTAMP NOT NULL, "total" numeric(12,2) NOT NULL, "paid_amount" numeric(12,2) NOT NULL DEFAULT '0', "balance" numeric(12,2) NOT NULL DEFAULT '0', "status" "public"."purchases_status_enum" NOT NULL DEFAULT 'OPEN', "note" character varying(255), "cancel_reason" character varying(255), "cancelled_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1d55032f37a34c6eceacbbca6b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "document" character varying(60), "phone" character varying(30), "email" character varying(160), "address" character varying(255), "notes" text, "is_active" boolean NOT NULL DEFAULT true, "store_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_batch_allocations_reference_type_enum" AS ENUM('PRODUCT_INITIAL', 'MANUAL_ENTRY', 'PURCHASE', 'SALE', 'ORDER', 'ORDER_CANCEL', 'ADJUSTMENT', 'RETURN', 'LEGACY')`);
        await queryRunner.query(`CREATE TABLE "inventory_batch_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batch_id" uuid NOT NULL, "product_id" uuid NOT NULL, "reference_type" "public"."inventory_batch_allocations_reference_type_enum" NOT NULL, "reference_id" uuid NOT NULL, "reference_item_id" uuid, "quantity" integer NOT NULL, "unit_cost_snapshot" numeric(12,2) NOT NULL, "expires_at_snapshot" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0ebc7c72cfa65d5ee56211afc1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_batches_status_enum" AS ENUM('ACTIVE', 'DEPLETED', 'EXPIRED', 'BLOCKED')`);
        await queryRunner.query(`CREATE TABLE "inventory_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "store_id" uuid, "supplier_id" uuid, "purchase_id" uuid, "purchase_item_id" uuid, "batch_code" character varying(120), "received_at" TIMESTAMP NOT NULL, "expires_at" TIMESTAMP, "unit_cost" numeric(12,2) NOT NULL, "initial_quantity" integer NOT NULL, "available_quantity" integer NOT NULL, "status" "public"."inventory_batches_status_enum" NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b670b7f687d8b8c58ef8d4629a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_movements_movement_type_enum" AS ENUM('IN', 'OUT', 'ADJUSTMENT', 'SALE', 'ORDER', 'ORDER_CANCEL')`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_movements_reference_type_enum" AS ENUM('PRODUCT_INITIAL', 'MANUAL_ENTRY', 'PURCHASE', 'SALE', 'ORDER', 'ORDER_CANCEL', 'ADJUSTMENT', 'RETURN', 'LEGACY')`);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "batch_id" uuid, "movement_type" "public"."inventory_movements_movement_type_enum" NOT NULL, "quantity_delta" integer NOT NULL, "reference_type" "public"."inventory_movements_reference_type_enum", "reference_id" uuid, "unit_cost_snapshot" numeric(12,2), "note" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menu_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_124ae987900336f983881cb04e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "description" text NOT NULL, "sku" character varying(80), "price" numeric(12,2) NOT NULL, "cost" numeric(12,2), "compare_at_price" numeric(12,2), "image_url" character varying(500), "is_active" boolean NOT NULL DEFAULT true, "show_stock" boolean NOT NULL DEFAULT false, "is_perishable" boolean NOT NULL DEFAULT false, "track_batches" boolean NOT NULL DEFAULT true, "low_stock_threshold" integer, "brand" character varying(120), "tags" text, "unit" character varying(50), "weight" numeric(10,3), "width" numeric(10,2), "height" numeric(10,2), "depth" numeric(10,2), "weight_unit" character varying(10), "dimensions_unit" character varying(10), "category_id" uuid NOT NULL, "store_id" uuid, "menu_category_id" uuid, "supplier_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(12,2) NOT NULL, "line_total" numeric(12,2) NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('PENDING', 'PAID', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_delivery_method_enum" AS ENUM('DELIVERY', 'PICKUP')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_status_enum" AS ENUM('NONE', 'SUBMITTED', 'CONFIRMED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'PENDING', "total" numeric(12,2) NOT NULL, "delivery_method" "public"."orders_delivery_method_enum" DEFAULT 'PICKUP', "delivery_address" text, "delivery_city" character varying(120), "delivery_department" character varying(120), "delivery_notes" text, "delivery_lat" double precision, "delivery_lng" double precision, "coupon_code" character varying(50), "discount_amount" numeric(12,2) NOT NULL DEFAULT '0', "payment_method_type" character varying(120), "payment_reference" character varying(200), "payment_evidence_image_path" character varying(500), "payment_status" "public"."orders_payment_status_enum" NOT NULL DEFAULT 'NONE', "payment_confirmed_at" TIMESTAMP, "payment_confirmed_by_user_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customer_ledger_entries_type_enum" AS ENUM('CREDIT_SALE', 'PAYMENT', 'ADJUSTMENT')`);
        await queryRunner.query(`CREATE TABLE "customer_ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "type" "public"."customer_ledger_entries_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "note" character varying(255), "reference_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_85afa229bb092b5e50f743b4ddc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(120) NOT NULL, "lastName" character varying(120) NOT NULL, "email" character varying(160) NOT NULL, "phone" character varying(30), "credit_enabled" boolean NOT NULL DEFAULT false, "credit_limit" numeric(12,2), "credit_balance" numeric(12,2) NOT NULL DEFAULT '0', "user_id" integer, "store_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_11d81cd7be87b6f8865b0cf7661" UNIQUE ("user_id"), CONSTRAINT "REL_11d81cd7be87b6f8865b0cf766" UNIQUE ("user_id"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_customers_store_email_unique" ON "customers" ("store_id", "email") WHERE "store_id" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."stores_delivery_options_enum" AS ENUM('DELIVERY', 'PICKUP', 'BOTH')`);
        await queryRunner.query(`CREATE TYPE "public"."stores_font_style_enum" AS ENUM('MODERN', 'CLASSIC', 'PLAYFUL')`);
        await queryRunner.query(`CREATE TYPE "public"."stores_button_style_enum" AS ENUM('ROUNDED', 'SHARP', 'PILL')`);
        await queryRunner.query(`CREATE TYPE "public"."stores_layout_style_enum" AS ENUM('GRID', 'LIST')`);
        await queryRunner.query(`CREATE TYPE "public"."stores_cover_style_enum" AS ENUM('GRADIENT', 'SOLID', 'MINIMAL')`);
        await queryRunner.query(`CREATE TYPE "public"."stores_store_type_enum" AS ENUM('STORE', 'RESTAURANT')`);
        await queryRunner.query(`CREATE TABLE "stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "slug" character varying(180) NOT NULL, "logo_url" character varying(500), "banner_url" character varying(500), "primary_color" character varying(20), "secondary_color" character varying(20), "description" text, "phone" character varying(30), "whatsapp_number" character varying(30), "delivery_options" "public"."stores_delivery_options_enum" NOT NULL DEFAULT 'BOTH', "accent_color" character varying(20), "bg_color" character varying(20), "text_color" character varying(20), "font_style" "public"."stores_font_style_enum" NOT NULL DEFAULT 'MODERN', "button_style" "public"."stores_button_style_enum" NOT NULL DEFAULT 'ROUNDED', "layout_style" "public"."stores_layout_style_enum" NOT NULL DEFAULT 'GRID', "cover_style" "public"."stores_cover_style_enum" NOT NULL DEFAULT 'GRADIENT', "email" character varying(160), "store_type" "public"."stores_store_type_enum" NOT NULL DEFAULT 'STORE', "menu_pdf_url" character varying(500), "is_active" boolean NOT NULL DEFAULT true, "is_system" boolean NOT NULL DEFAULT false, "is_adult_content" boolean NOT NULL DEFAULT false, "is_premium_advertiser" boolean NOT NULL DEFAULT false, "advertising_expires_at" TIMESTAMP, "subscription_expires_at" TIMESTAMP, "user_id" integer, "wpp_notifications_enabled" boolean NOT NULL DEFAULT true, "wpp_api_key" character varying(100), "lat" double precision, "lng" double precision, "address_text" character varying(300), "payment_instructions" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_790b2968701a6ff5ff383237765" UNIQUE ("slug"), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."store_subscriptions_status_enum" AS ENUM('TRIAL', 'ACTIVE', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."store_subscriptions_payment_method_enum" AS ENUM('CASH', 'TRANSFER', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "store_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "status" "public"."store_subscriptions_status_enum" NOT NULL DEFAULT 'ACTIVE', "start_date" date NOT NULL, "end_date" date NOT NULL, "paid_amount" numeric(12,2) NOT NULL, "payment_method" "public"."store_subscriptions_payment_method_enum" NOT NULL DEFAULT 'CASH', "notes" text, "receipt_url" character varying(500), "registered_by_user_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_325400ee6964d5c2a50b68d58e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(80) NOT NULL, "description" text, "price_monthly" numeric(12,2) NOT NULL, "duration_days" integer NOT NULL DEFAULT '30', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sales_payment_method_enum" AS ENUM('CASH', 'CREDIT')`);
        await queryRunner.query(`CREATE TYPE "public"."sales_delivery_type_enum" AS ENUM('LOCAL', 'SHIPPING')`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_method" "public"."sales_payment_method_enum" NOT NULL DEFAULT 'CASH', "customer_id" uuid, "store_id" uuid, "cash_session_id" uuid, "total" numeric(12,2) NOT NULL, "guest_name" character varying(160), "guest_phone" character varying(30), "guest_doc_type" character varying(10), "guest_doc" character varying(30), "delivery_type" "public"."sales_delivery_type_enum", "delivery_address" character varying(300), "delivery_city" character varying(100), "delivery_notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sale_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(12,2) NOT NULL, "line_total" numeric(12,2) NOT NULL, CONSTRAINT "PK_5a7dc5b4562a9e590528b3e08ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "store_id" uuid NOT NULL, "order_id" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "is_visible" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ef82c9a88c4d622b5ffa60ae9a7" UNIQUE ("customer_id", "order_id"), CONSTRAINT "PK_2da716d0ce9c18fcde79757bbe5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "review_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "review_id" uuid NOT NULL, "url" character varying(500) NOT NULL, CONSTRAINT "PK_dfb8fbc1b0534f20de489a64358" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "product_id" uuid NOT NULL, "order_id" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "is_visible" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer, "endpoint" text NOT NULL, "p256dh" text NOT NULL, "auth_key" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6771f119f1c06d2ccf38f23866" ON "push_subscriptions" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "product_favorites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "product_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_product_favorites_customer_product" UNIQUE ("customer_id", "product_id"), CONSTRAINT "PK_731c5d4877a8511f3bd5d7e6c10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."store_invitations_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "store_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(160) NOT NULL, "token_hash" character varying(64) NOT NULL, "status" "public"."store_invitations_status_enum" NOT NULL DEFAULT 'PENDING', "invited_by" integer NOT NULL, "expires_at" TIMESTAMP NOT NULL, "accepted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_efb6ddddde0a543730e3fe1bf55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_videos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "video_url" character varying(500) NOT NULL, "video_type" character varying(20) NOT NULL, "title" character varying(200), "order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705a4fd6bc408b0a8a874f09d7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "image_url" character varying(500) NOT NULL, "order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_type_enum" AS ENUM('PERCENTAGE', 'FIXED')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "type" "public"."coupons_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "min_order_amount" numeric(12,2), "max_uses" integer, "used_count" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recoverTokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "tokenHash" character varying NOT NULL, "purpose" character varying(30) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, "attempts" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_833907ce126db93456fe50f0af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cash_sessions_status_enum" AS ENUM('OPEN', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "cash_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "user_id" integer NOT NULL, "opening_amount" numeric(12,2) NOT NULL, "expected_amount" numeric(12,2) NOT NULL DEFAULT '0', "closing_amount" numeric(12,2), "difference" numeric(12,2), "status" "public"."cash_sessions_status_enum" NOT NULL DEFAULT 'OPEN', "opened_at" TIMESTAMP NOT NULL DEFAULT now(), "closed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_946ea5ce864b10fb70162708448" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cash_movements_type_enum" AS ENUM('MANUAL_IN', 'MANUAL_OUT', 'ADJUSTMENT')`);
        await queryRunner.query(`CREATE TABLE "cash_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cash_session_id" uuid NOT NULL, "type" "public"."cash_movements_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "reason" character varying(255) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_25faead19e1ff74153a01604d37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."store_advertisements_payment_method_enum" AS ENUM('CASH', 'TRANSFER', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."store_advertisements_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "store_advertisements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "paid_amount" numeric(12,2) NOT NULL DEFAULT '0', "payment_method" "public"."store_advertisements_payment_method_enum" NOT NULL DEFAULT 'CASH', "status" "public"."store_advertisements_status_enum" NOT NULL DEFAULT 'ACTIVE', "notes" text, "registered_by_user_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e9b37b39ac0edb0b9a751956b45" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "app_config" ("id" integer NOT NULL, "is_access_blocked" boolean NOT NULL DEFAULT false, "blocked_message" text, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ccdbb6f00e8113d8953476a507b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer, "action" character varying(80) NOT NULL, "entity" character varying(80) NOT NULL, "reference_id" character varying(120), "detail" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_5848ba82e61b83e2aa416447a15" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_607211d59b13e705a673a999ab5" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_43694b2fa800ce38d2da9ce74d6" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_b0089820b7452d8e84b5d1fda65" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_d5fec047f705d5b510c19379b95" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_dec353eded97300e37299b03031" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_7b65a15acf2e34137794564e1b0" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batch_allocations" ADD CONSTRAINT "FK_c7d6bc285f88ea0eb8073f945cc" FOREIGN KEY ("batch_id") REFERENCES "inventory_batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batch_allocations" ADD CONSTRAINT "FK_8bd85db1496d6fcc82af15c7447" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_9350781ae7a615d184b56660e31" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_f89c1b7896df2aeed33b59eedf6" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_1ffb2085644430dd32b5d92152a" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_bc4506b2145394d938ae8c69241" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_8b54f51da10e4004007730d16fb" FOREIGN KEY ("purchase_item_id") REFERENCES "purchase_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_5c3bec1682252c36fa161587738" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_0d8d237c78afa95bb19afcb5172" FOREIGN KEY ("batch_id") REFERENCES "inventory_batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_categories" ADD CONSTRAINT "FK_4913ff448312f5619a8f106560a" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_68863607048a1abd43772b314ef" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_0ec433c1e1d444962d592d86c86" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_2851169b75817c58b3812207ff5" FOREIGN KEY ("menu_category_id") REFERENCES "menu_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_ledger_entries" ADD CONSTRAINT "FK_b1222f1e9bf0d26bee5e6b685cf" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_2501b8750977dd4f4d06dfeff07" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_subscriptions" ADD CONSTRAINT "FK_d1de6b6f0c3e0e3d5437979086d" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_subscriptions" ADD CONSTRAINT "FK_5ade9daa686144654a5c5d71087" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_6c1fae113ae666969a94d79d637" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_c210a330b80232c29c2ad68462a" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_4ecae62db3f9e9cc9a368d57adb" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_reviews" ADD CONSTRAINT "FK_62aa140996c7cb29b7d59938ddc" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_reviews" ADD CONSTRAINT "FK_6514057b9e108d9eace56563fb6" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_reviews" ADD CONSTRAINT "FK_05c83eebf6df789a232531bde8a" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD CONSTRAINT "FK_45b8671ec9f03b6682a52adb120" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_4dd42f48aa60ad8c0d5d5c4ea5b" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_e4b0ed40bdd0f318108612c2851" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_favorites" ADD CONSTRAINT "FK_3c0c5ef9341829d2b54f75622a5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_favorites" ADD CONSTRAINT "FK_a0b0826f5c155ce481fb0d2017b" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_videos" ADD CONSTRAINT "FK_4bee29aa25fc3adccf1653731df" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_8a9ef7c18d94cea6ee0e43182a3" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD CONSTRAINT "FK_fa6a0c146567090acf8a03e01c2" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_advertisements" ADD CONSTRAINT "FK_aad997bf996e05fca2a519a4c5f" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "store_advertisements" DROP CONSTRAINT "FK_aad997bf996e05fca2a519a4c5f"`);
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP CONSTRAINT "FK_fa6a0c146567090acf8a03e01c2"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_8a9ef7c18d94cea6ee0e43182a3"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "product_videos" DROP CONSTRAINT "FK_4bee29aa25fc3adccf1653731df"`);
        await queryRunner.query(`ALTER TABLE "product_favorites" DROP CONSTRAINT "FK_a0b0826f5c155ce481fb0d2017b"`);
        await queryRunner.query(`ALTER TABLE "product_favorites" DROP CONSTRAINT "FK_3c0c5ef9341829d2b54f75622a5"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_e4b0ed40bdd0f318108612c2851"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_4dd42f48aa60ad8c0d5d5c4ea5b"`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP CONSTRAINT "FK_45b8671ec9f03b6682a52adb120"`);
        await queryRunner.query(`ALTER TABLE "store_reviews" DROP CONSTRAINT "FK_05c83eebf6df789a232531bde8a"`);
        await queryRunner.query(`ALTER TABLE "store_reviews" DROP CONSTRAINT "FK_6514057b9e108d9eace56563fb6"`);
        await queryRunner.query(`ALTER TABLE "store_reviews" DROP CONSTRAINT "FK_62aa140996c7cb29b7d59938ddc"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_4ecae62db3f9e9cc9a368d57adb"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_c210a330b80232c29c2ad68462a"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_6c1fae113ae666969a94d79d637"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5"`);
        await queryRunner.query(`ALTER TABLE "store_subscriptions" DROP CONSTRAINT "FK_5ade9daa686144654a5c5d71087"`);
        await queryRunner.query(`ALTER TABLE "store_subscriptions" DROP CONSTRAINT "FK_d1de6b6f0c3e0e3d5437979086d"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_2501b8750977dd4f4d06dfeff07"`);
        await queryRunner.query(`ALTER TABLE "customer_ledger_entries" DROP CONSTRAINT "FK_b1222f1e9bf0d26bee5e6b685cf"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_2851169b75817c58b3812207ff5"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_0ec433c1e1d444962d592d86c86"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_68863607048a1abd43772b314ef"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "menu_categories" DROP CONSTRAINT "FK_4913ff448312f5619a8f106560a"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_0d8d237c78afa95bb19afcb5172"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_5c3bec1682252c36fa161587738"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_8b54f51da10e4004007730d16fb"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_bc4506b2145394d938ae8c69241"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_1ffb2085644430dd32b5d92152a"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_f89c1b7896df2aeed33b59eedf6"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_9350781ae7a615d184b56660e31"`);
        await queryRunner.query(`ALTER TABLE "inventory_batch_allocations" DROP CONSTRAINT "FK_8bd85db1496d6fcc82af15c7447"`);
        await queryRunner.query(`ALTER TABLE "inventory_batch_allocations" DROP CONSTRAINT "FK_c7d6bc285f88ea0eb8073f945cc"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_7b65a15acf2e34137794564e1b0"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_dec353eded97300e37299b03031"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_d5fec047f705d5b510c19379b95"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_b0089820b7452d8e84b5d1fda65"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_43694b2fa800ce38d2da9ce74d6"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_607211d59b13e705a673a999ab5"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_5848ba82e61b83e2aa416447a15"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "app_config"`);
        await queryRunner.query(`DROP TABLE "store_advertisements"`);
        await queryRunner.query(`DROP TYPE "public"."store_advertisements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."store_advertisements_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "cash_movements"`);
        await queryRunner.query(`DROP TYPE "public"."cash_movements_type_enum"`);
        await queryRunner.query(`DROP TABLE "cash_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."cash_sessions_status_enum"`);
        await queryRunner.query(`DROP TABLE "recoverTokens"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_type_enum"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP TABLE "product_videos"`);
        await queryRunner.query(`DROP TABLE "store_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."store_invitations_status_enum"`);
        await queryRunner.query(`DROP TABLE "product_favorites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6771f119f1c06d2ccf38f23866"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "review_images"`);
        await queryRunner.query(`DROP TABLE "store_reviews"`);
        await queryRunner.query(`DROP TABLE "sale_items"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TYPE "public"."sales_delivery_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sales_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP TABLE "store_subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."store_subscriptions_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."store_subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "stores"`);
        await queryRunner.query(`DROP TYPE "public"."stores_store_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stores_cover_style_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stores_layout_style_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stores_button_style_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stores_font_style_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stores_delivery_options_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customers_store_email_unique"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "customer_ledger_entries"`);
        await queryRunner.query(`DROP TYPE "public"."customer_ledger_entries_type_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_delivery_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "menu_categories"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_movements_reference_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_movements_movement_type_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_batches"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_batches_status_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_batch_allocations"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_batch_allocations_reference_type_enum"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "purchases"`);
        await queryRunner.query(`DROP TYPE "public"."purchases_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_payments"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_payments_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_items"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
